name: Deploy to Dev

on:
  push:
    branches:
      - dev   # only run when pushing to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files to Hostinger (Dev)
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SOURCE: "./"
          TARGET: "${{ secrets.DEV_APP_DIR }}"

      - name: Run Laravel optimizations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DEV_APP_DIR }}
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache